### PR TITLE
Add lint flag to ignore circular references for polymorphic definitions and arrays.

### PR DESCRIPTION
**Pull request by eli-l**

### CODE REVIEW

**Comment by eli-l** [comment]
This works well with [patched libopenapi](https://github.com/pb33f/libopenapi/pull/241)

**Review by daveshanley — CHANGES_REQUESTED** [review]
The only thing we need to do now is to bump the version of `libopenapi` and I can merge both this and #430 together.

**Comment by daveshanley** [comment]
I am assuming once you bump the version of libopenapi, the failing test will pass.

**Comment by eli-l** [comment]
@daveshanley That's mostly it. Looking forward to the release.

**Comment by daveshanley** [comment]
I think you need to run `go mod tidy`

**Comment by eli-l** [comment]
@daveshanley Yes, for some reason go.sum was not up to date.

**Review by daveshanley — APPROVED** [review]
LGTM thank you for the upgrade!

**Comment by eli-l** [comment]
You're welcome @daveshanley. It would be great you'd mention these flags in the documentation.

**Comment by daveshanley** [comment]
Done.

**Pull request merged**
