### PR TITLE
Added initial basic language server implementation

### PR DESCRIPTION
**Pull request by KDanisme**
Draft of a language server for vacuum for getting real time diagnostics.
Its super minimal, and currently only shows diagnostics using the basic ruleset.

https://github.com/daveshanley/vacuum/assets/38726107/b52e79f6-913c-46b8-86df-bc628589a087

I do have a few issues with this pr:

1. Some dependencees were added, not sute how you feel about that
2. without a config file, it will be very tedious to have custom rules/rulesets for the language server, you would have to reconfigure your language server client every time you enter a new project with a different configuration.

I saw there were plans for a config file, i would be glad to help out where i can.

Regarding the code, this is my first go code so please excuse me if i made any stupid mistakes.

### CODE REVIEW

**Comment by daveshanley** [comment]
Oh wow, this is great! What great potential. I will review ASAP.

**Comment by KDanisme** [comment]
Ill add some docs and clean the code.
Regarding integration, i would like to add this as an "official" neovim language server which can be downloaded using a ls manager.
Ill look into vscode and intellij as well.

I don't see a point in merging this (unless you want to)
At least not until the config file.
I would be happy to work on it and merge this one after,unless you have some specific plans in mind.

**Comment by daveshanley** [comment]
Sorry about the delay in my response, I was away for the weekend. 

OK so a config feature sounds right here to make this work correctly. We already use https://github.com/spf13/viper in the project, so it makes sense to use that for pulling out the configuration variables. 

Here would be my requirements for the feature:

- Should support any type of markup file (this is where viper steps in)
- Should have a default lookup of ./vacuum.config.* and ~/vacuum.config.*
- Should allow setting of all root flags (https://github.com/daveshanley/vacuum/blob/main/cmd/root.go#L51)
- Should allow setting of individual command flags (for example: https://github.com/daveshanley/vacuum/blob/main/cmd/lint.go#L198)
- Command flags should be kept in top-level sections of the config (for example)

```
lint:
  details: true
  category: schemas
  ...
```

**Comment by KDanisme** [comment]
Can you elaborate on the ` ~/vacuum.config.*` directory.
Why should vacuum have a personal configuration and not only a per project configuration?

Im not aware of any linters that support this.
Off the top of my head [Detekt](https://github.com/detekt/detekt/issues/1262) is a linter i use for kotlin which also doesnt do this.

**Comment by KDanisme** [comment]
Also, you said the project already uses Viper, im assuming you meant cobra, and that viper is a good fit with cobra.
Because i didnt see any usage of viper (besides you TODO comments for the config file)

**Comment by daveshanley** [comment]
> Also, you said the project already uses Viper, im assuming you meant cobra, and that viper is a good fit with cobra. Because i didnt see any usage of viper (besides your TODO comments for the config file)
> 
> Anyway, i started working on it, ill have a pr ready by tomorrow, maybe even today

Yes, I meant to say that we have cobra in the library, which depends on viper, so there is no new dependency to add. 

Looking forward to the PR, this will be a great new set of features.

**Comment by KDanisme** [comment]
> > Can you elaborate on the ` ~/vacuum.config.*` directory. Why should vacuum have a personal configuration and not only a per project configuration?
> > Im not aware of any linters that support this. Off the top of my head [Detekt](https://github.com/detekt/detekt/issues/1262) is a linter i use for kotlin which also doesnt do this.
> 
> It's a personal preference, I always like a tool that considers 'me' and not 'where I am'. So I like a default behavior always applied to a tool. However, it should always be over-ridden by a config that is in the working directory - it's like a soft fallback config.

If you do insist on going this route.
Do we want this to comply to [basedir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)?

**Comment by daveshanley** [comment]
> > > Can you elaborate on the ` ~/vacuum.config.*` directory. Why should vacuum have a personal configuration and not only a per project configuration?
> > > Im not aware of any linters that support this. Off the top of my head [Detekt](https://github.com/detekt/detekt/issues/1262) is a linter i use for kotlin which also doesnt do this.
> > 
> > 
> > It's a personal preference, I always like a tool that considers 'me' and not 'where I am'. So I like a default behavior always applied to a tool. However, it should always be over-ridden by a config that is in the working directory - it's like a soft fallback config.
> 
> If you do insist on going this route. Do we want this to comply to [basedir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)?

Yes, this is a good idea.

**Comment by daveshanley** [comment]
oh no! what happened to this?

**Comment by KDanisme** [comment]
> oh no! what happened to this?

Dont worry i simply made a mess of my forked so i moved some branches around,
Ill create a new one once config file is merged

**Comment by daveshanley** [comment]
@KDanisme 

The configuration feature was merged into vacuum. Is there a possibility to get this re-submitted? I'd like to expose this functionality, I'd rather you be the contributor rather than just lift the code you've already written.

**Comment by KDanisme** [comment]
@daveshanley Hi yes,
Sorry i was busy with work.
I was simply putting this off because i wanted to add some comments and docs.
Regarding our previous talk.
I was in the middle of creating a vscode plugin for this language server, including adding a PR to neovim language server plugins.

Do you want the vscode plugin to be in this repo as well?

**Comment by daveshanley** [comment]
Yes, I would like to keep it all together, and add a build to publish it accordingly.

**Comment by KDanisme** [comment]
Then i will add the vscode and intellij extensions in different PRs

**Comment by daveshanley** [comment]
Nice! This will be very exciting to see.

**Pull request closed without merging**
